name: 'PR to DEV'

on:
  push:
    branches:
      - 'feature/*'       # matches every branch containing a single '/'

jobs:
  terraform:
    name: 'Open PR to DEV'
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: us-east-1
      APPLICATION_NAME: memegen
      MODELS_BUCKET_NAME: fiap-ml-models-monorepo-bucket
      GH_TOKEN: ${{ github.token }}

    defaults:
      run:
        shell: bash
        working-directory: ./infra

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Echo App Contents
        run: tree ../app

      - name: Install Astral UV Package Manager
        uses: astral-sh/setup-uv@v5

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: "./app/pyproject.toml"

      - name: Echo Python Version
        run: python -V

      - name: Install project dependencies
        run: uv sync --locked --all-extras --dev --directory ../app

      - name: Run tests
        run: uv run pytest --directory ../app tests

      - name: Terraform Init
        run: terraform init -backend-config="key=$APPLICATION_NAME-develop.tfstate"

      - name: Terraform Plan
        run: terraform plan -var 'environment=develop' -var "bucket_name=$MODELS_BUCKET_NAME" -input=false

      - name: Create Pull Request to Develop
        run: |
          gh pr create --base develop --title "Automated PR to Develop" --body "This PR was created automatically by GitHub Actions."